name: Training to Workflows
on: [push, workflow_dispatch]

jobs:
  First-job:
    name: initialize start-time
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          name: calculation
          path: time
      - name: Upload time end
        run: date +%s > time_end.txt
      - name: setDate
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: time_end.txt
      - name: load the var
        run: date +%s > start.txt
      - name: Show
        run: cat start.txt
      - name: Test Date
        run: |
          echo "`DATE=date +%Y-%m`" >> $GITHUB_OUTPUT
          echo $Date
      - name: Explore Context
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      - name: Explore Env
        run: echo $JSON
        env:
          JSON: ${{ toJSON(env) }}
