name: Training to Workflows
on: [push, workflow_dispatch]

jobs:
  First-job:
    name: initialize start-time
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          name: calculation
          path: time
      - name: load the var
        run: date +%s > start.txt
      - name: Show
        run: cat start.txt
      - name: Test Date
        run: |
          Date=date +%Y-%m
          echo $Date
